### ISSUE TITLE
실수로 친 타자에 오류 발생

### ISSUE THREAD

**Issue by See-Y** [makerj/heconvert#2]
from heconvert.converter import *

print(e2h('RK'))

위와 같은 상황에서는 타자를 빠르게 치다보니 원래 'Rk' 입력되어야 할 것이 'RK'라고 입력이 되었을 뿐인데 이에 오류가 발생하게 됩니다.
한가지 제안드리는 것은 예외처리를 통해 'K'와 같은 글자가 기존에 없다면 lower()를 적용시켜보는 것은 어떨까요?

**Comment by makerj** [comment]
이슈 올려주셔서 감사합니다.

또 다른 예외가 나왔네요. `K` 키에 매핑되는 한글이 없어서 발생한 문제로 보이고, 내부 예외 처리 코드 추가를 통해 간단하게 수정할 수 있는 이슈입니다.

`lower()` 를 사용하는 것도 좋은 방법이지만... 결과물이 달라지게 됩니다. 예를 들어 RK는 'ㄲK'가 아니라 '까'로 변환됩니다. 사용자는 '까'로 변환되는걸 좋아할 수 있겠지만, 라이브러리 입장에서는 ㄲK로 변환하는 것이 일관성을 유지하는데 도움이 됩니다.

**Comment by makerj** [comment]
Fixed by commit 6438d9b
